#
# iniparser doc Makefile
#

all: html

html:
	doxygen iniparser.dox
	rm -f ../html/annotated.html
	rm -f ../html/classes.html
	rm -f ../html/doxygen.gif
	rm -f ../html/files.html
	rm -f ../html/functions.html
	rm -f ../html/globals.html
	rm -f ../html/iniparser_main.html

